name: 'Kingly paragraph button'
type: 'Site'
description: 'Configures a Kingly button paragraph type and its fields.'
install:
  - paragraphs
  - link
  - options
  - paragraph_view_mode
config:
  strict: false
